language: go

go:
- 1.12.x

env:
  - GO111MODULE=on

git:
  depth: 1

notifications:
  email: false

before_install:
  - go mod download

script:
  - make check  
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)