---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kheer-admin
  namespace: kheer-sys
  labels:
    app: kheer
    component: sys
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kheer-user
  namespace: kheer-ops
  labels:
    app: kheer
    component: ops
